### ISSUE TITLE
(TLoU2) Load Remover not pausing on Loading Screens

### ISSUE THREAD

**Issue by AnarchinGaming** [blegas78/autoSplitters#1]
Hi,

My Load Remover seems to be working perfectly well for the most part. Pauses on pause screens and black screens, but when the loading screen for TLoU2 fades in, the timer starts counting again. Any ideas why this is?

**Comment by blegas78** [comment]
Thanks for asking me this!  This is the first time I've heard of this happening.  Does this happen all the time?  Are you able to share a video of it exhibiting this behavior?

**Comment by AnarchinGaming** [comment]
Yes, let me record it really quick.

**Comment by AnarchinGaming** [comment]
https://youtu.be/O4d1cHjW5GA

**Comment by AnarchinGaming** [comment]
So, I believe I fixed it. I use the Elgato Game Capture, and, apparently, it's slightly too bright for the load remover to recognize the loading screen. I lowered the brightness in the Game Capture settings to -1, and it works just fine lol. I appreciate your time in trying to help figure this out!

**Comment by blegas78** [comment]
Ah!  Thank you for letting me know how you got it to work!

**Comment by AnarchinGaming** [comment]
So, new issue lol. I streamed my first run today, and it appears the loading screen will keep the timer paused for roughly 90% of the time. But occasionally the timer will start up again and I'm not entirely sure why. It only added 7+ minutes to the run but I couldn't figure out what the issue was since it seemed inconsistent.
