### ISSUE TITLE
Load Remover not pausing on Load Screens

### ISSUE THREAD

**Issue by AnarchinGaming** [blegas78/autoSplitters#2]
So, a new issue. I streamed my first run, and it appears the loading screen will keep the timer paused for roughly 90% of the time. But occasionally the timer will start up again and I'm not entirely sure why. It only added 7+ minutes to the run but I couldn't figure out what the issue was since it seemed inconsistent.

**Comment by alexjlockwood** [comment]
@blegas78 Should we consider it fixed by #3 until it pops up again?

**Comment by blegas78** [comment]
Makes sense to me!
